### ISSUE TITLE
won't build on Debian 9.3

### ISSUE THREAD

**Issue by seefood** [hamishcoleman/spectre-tests#1]
```
uma:/usr/src/spectre-tests# make
cc -g -Wall -o spectre spectre.c
In file included from /usr/lib/gcc/i686-linux-gnu/6/include/xmmintrin.h:1249:0,
                 from /usr/lib/gcc/i686-linux-gnu/6/include/x86intrin.h:33,
                 from spectre.c:10:
spectre.c: In function ‘readMemoryByte’:
/usr/lib/gcc/i686-linux-gnu/6/include/emmintrin.h:1479:1: error: inlining failed in call to always_inline ‘_mm_clflush’: target specific option mismatch
 _mm_clflush (void const *__A)
 ^~~~~~~~~~~
spectre.c:101:7: note: called from here
       _mm_clflush( & array2[i * 512]); /* intrinsic for clflush instruction */
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/lib/gcc/i686-linux-gnu/6/include/xmmintrin.h:1249:0,
                 from /usr/lib/gcc/i686-linux-gnu/6/include/x86intrin.h:33,
                 from spectre.c:10:
/usr/lib/gcc/i686-linux-gnu/6/include/emmintrin.h:1479:1: error: inlining failed in call to always_inline ‘_mm_clflush’: target specific option mismatch
 _mm_clflush (void const *__A)
 ^~~~~~~~~~~
spectre.c:106:7: note: called from here
       _mm_clflush( & array1_size);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Makefile:17: recipe for target 'spectre' failed
make: *** [spectre] Error 1
```

**Comment by hamishcoleman** [comment]
the _mm_clflush function is not available by default on the i686 architecture.

I have updated the makefile to enable that - so you should be able to at least build the test now.

I found a 32bit system and did a quick test, but the test doesnt seem to be working, so you might need to dig further

**Comment by seefood** [comment]
```
uma:/usr/src/spectre-tests# ./spectre
Reading 40 bytes:
Illegal instruction
uma:/usr/src/spectre-tests# ./spectre_pthread 
Reading 40 bytes:
Reading at malicious_x = 0xffffdd80... Unclear: 0xB4=’?’ score=995 (second best: 0x2B score=992)
[...]
Reading at malicious_x = 0xffffdda7... Unclear: 0xB4=’?’ score=997 (second best: 0x61 score=996)
counter thread finished
```

ok, it builds, not sure what to make of the output.
Interesting facts:
1. the CPU is Xeon  E5310, it may actually be old enough to not be vulnerable.
2. My kernel is the latest from Debian but no KPTI patch in the config, some folks of #Debian on freenode told me that 64 bit mode is necessary for meltdown (maybe also spectre?) so the fact I have a legacy system with a 32 bit kernel actually saves my ass. I'm looking for more info to validate that claim. If true, it means downgrading to a 32 bit OS is saving you the performance hit of the patch if you have a CPU that can address all your RAM in 32 bit mode.

**Comment by hamishcoleman** [comment]
I got very similar output to you - and clearly it is not finding any ossifrages, squeamish or other.  You could try playing with the CACHE_HIT_THRESHOLD - I found the pthreads version was more susceptible to variations in that number.

The illegal instruction is due to the rdtscp - which I get just like you, but I know I get it because my virtual machine has not been given the rdtscp feature.

As far as I know, all Xeon CPUs are vulnerable - but I'm just going from the published data there.  The two vulnerabilities are not tied to 64bit/32bit kernels, so there should be a way to make this test program show the issue.

Sorry I cannot be of more help, but I have not really tried to test any 32bit systems :-(

**Comment by seefood** [comment]
I had to run it on a new CPU to see what I was missing, this is the output. (kernel has KPTI, but Spectre is not covered of course)
```
 ./spectre_pthread 
Reading 40 bytes:
Reading at malicious_x = 0xffffffffffdff0a8... Unclear: 0x54=’T’ score=999 (second best: 0x52 score=986)
Reading at malicious_x = 0xffffffffffdff0a9... Unclear: 0x68=’h’ score=997 (second best: 0x52 score=987)
Reading at malicious_x = 0xffffffffffdff0aa... Unclear: 0x65=’e’ score=994 (second best: 0xB3 score=979)
Reading at malicious_x = 0xffffffffffdff0ab... Unclear: 0x20=’ ’ score=999 (second best: 0xD0 score=980)
Reading at malicious_x = 0xffffffffffdff0ac... Unclear: 0x4D=’M’ score=998 (second best: 0xB1 score=984)
Reading at malicious_x = 0xffffffffffdff0ad... Unclear: 0x61=’a’ score=997 (second best: 0xAF score=986)
Reading at malicious_x = 0xffffffffffdff0ae... Unclear: 0x67=’g’ score=998 (second best: 0x75 score=977)
Reading at malicious_x = 0xffffffffffdff0af... Unclear: 0x69=’i’ score=999 (second best: 0x53 score=975)
Reading at malicious_x = 0xffffffffffdff0b0... Unclear: 0x63=’c’ score=998 (second best: 0x75 score=973)
Reading at malicious_x = 0xffffffffffdff0b1... Unclear: 0x20=’ ’ score=997 (second best: 0x6E score=981)
Reading at malicious_x = 0xffffffffffdff0b2... Unclear: 0x57=’W’ score=998 (second best: 0xB1 score=979)
Reading at malicious_x = 0xffffffffffdff0b3... Unclear: 0x6F=’o’ score=998 (second best: 0xCE score=975)
Reading at malicious_x = 0xffffffffffdff0b4... Unclear: 0x72=’r’ score=998 (second best: 0x5C score=971)
Reading at malicious_x = 0xffffffffffdff0b5... Unclear: 0x64=’d’ score=998 (second best: 0x4E score=981)
Reading at malicious_x = 0xffffffffffdff0b6... Unclear: 0x73=’s’ score=998 (second best: 0xBF score=975)
Reading at malicious_x = 0xffffffffffdff0b7... Unclear: 0x20=’ ’ score=998 (second best: 0x6E score=977)
Reading at malicious_x = 0xffffffffffdff0b8... Unclear: 0x61=’a’ score=999 (second best: 0x5B score=985)
Reading at malicious_x = 0xffffffffffdff0b9... Unclear: 0x72=’r’ score=999 (second best: 0xD0 score=981)
Reading at malicious_x = 0xffffffffffdff0ba... Unclear: 0x65=’e’ score=996 (second best: 0xB3 score=982)
Reading at malicious_x = 0xffffffffffdff0bb... Unclear: 0x20=’ ’ score=998 (second best: 0x6E score=977)
Reading at malicious_x = 0xffffffffffdff0bc... Unclear: 0x53=’S’ score=999 (second best: 0x54 score=989)
Reading at malicious_x = 0xffffffffffdff0bd... Unclear: 0x71=’q’ score=994 (second best: 0x75 score=978)
Reading at malicious_x = 0xffffffffffdff0be... Unclear: 0x75=’u’ score=999 (second best: 0xB9 score=978)
Reading at malicious_x = 0xffffffffffdff0bf... Unclear: 0x65=’e’ score=998 (second best: 0xB3 score=978)
Reading at malicious_x = 0xffffffffffdff0c0... Unclear: 0x61=’a’ score=999 (second best: 0xAF score=980)
Reading at malicious_x = 0xffffffffffdff0c1... Unclear: 0x6D=’m’ score=997 (second best: 0xBB score=981)
Reading at malicious_x = 0xffffffffffdff0c2... Unclear: 0x69=’i’ score=999 (second best: 0xD0 score=983)
Reading at malicious_x = 0xffffffffffdff0c3... Unclear: 0x73=’s’ score=999 (second best: 0xC5 score=973)
Reading at malicious_x = 0xffffffffffdff0c4... Unclear: 0x68=’h’ score=999 (second best: 0x52 score=981)
Reading at malicious_x = 0xffffffffffdff0c5... Unclear: 0x20=’ ’ score=999 (second best: 0xB6 score=967)
Reading at malicious_x = 0xffffffffffdff0c6... Unclear: 0x4F=’O’ score=999 (second best: 0xAF score=975)
Reading at malicious_x = 0xffffffffffdff0c7... Unclear: 0x73=’s’ score=999 (second best: 0xC1 score=988)
Reading at malicious_x = 0xffffffffffdff0c8... Unclear: 0x73=’s’ score=999 (second best: 0xC1 score=994)
Reading at malicious_x = 0xffffffffffdff0c9... Unclear: 0x69=’i’ score=999 (second best: 0x53 score=974)
Reading at malicious_x = 0xffffffffffdff0ca... Unclear: 0x66=’f’ score=996 (second best: 0xD0 score=977)
Reading at malicious_x = 0xffffffffffdff0cb... Unclear: 0x72=’r’ score=999 (second best: 0xB3 score=970)
Reading at malicious_x = 0xffffffffffdff0cc... Unclear: 0x61=’a’ score=999 (second best: 0xCE score=986)
Reading at malicious_x = 0xffffffffffdff0cd... Unclear: 0x67=’g’ score=999 (second best: 0xBB score=984)
Reading at malicious_x = 0xffffffffffdff0ce... Unclear: 0x65=’e’ score=998 (second best: 0xA4 score=988)
Reading at malicious_x = 0xffffffffffdff0cf... Unclear: 0x2E=’.’ score=997 (second best: 0x58 score=986)
counter thread finished
```
You will notice the column of guessed bytes spells out "The Magic Words are Squeemish Ossifrage." but on my 32 system (old Xeon) it guesses "!!!www!!!!!w!!w!!!!!w!!!!wwww!!wwww!ww!!".
So either 32 bit mode is not vulnerable (unlikely), the test doesn't cover 32 bit mode correctly, or the exploit for 32 bit is entirely different. To be sure I'll need to boot a 32 bit kernel on my modern laptop or a 64 bit kernel on my server and test again. Maybe I'll do it some time later.

For now I'm satisfied with not seeing my old Xeon listed here: https://www.techarp.com/guides/complete-meltdown-spectre-cpu-list/

**Comment by hamishcoleman** [comment]
I've just checked the CPU on the system I had which was hosting a 32bit VM (a Xeon E5440) - and it doesnt appear on that techarp list either, which might explain why the tests didnt work for me too.

**Comment by seefood** [comment]
you mean it works on the 64bit host but not inside the VM? that suggests an incomplete test then, not an immune CPU.

**Comment by hamishcoleman** [comment]
No, it didnt work on the 64bit host either - so hopefully thats a valid negative result for the CPU instead of an invalid test

**Comment by seefood** [comment]
:+1:
